global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'demo'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['localhost:9121']
